language: node_js
dist: trusty
sudo: required
node_js: stable

cache:
  directories:
    - ./exercises/chapter2/bower_components
    - ./exercises/chapter3/bower_components
    - ./exercises/chapter4/bower_components
    - ./exercises/chapter5/bower_components
    - ./exercises/chapter6/bower_components
    - ./exercises/chapter7/bower_components
    - ./exercises/chapter8/bower_components
    - ./exercises/chapter9/bower_components
    - ./exercises/chapter10/bower_components
    - ./exercises/chapter11/bower_components
    - ./exercises/chapter12/bower_components
    - ./exercises/chapter13/bower_components
    - ./exercises/chapter14/bower_components

env:
  - TEST_DIR=./exercises/chapter2/
  - TEST_DIR=./exercises/chapter3/
  - TEST_DIR=./exercises/chapter4/
  - TEST_DIR=./exercises/chapter5/
  - TEST_DIR=./exercises/chapter6/
  - TEST_DIR=./exercises/chapter7/
  - TEST_DIR=./exercises/chapter8/
  - TEST_DIR=./exercises/chapter9/
  - TEST_DIR=./exercises/chapter10/
  - TEST_DIR=./exercises/chapter11/
  - TEST_DIR=./exercises/chapter12/
  - TEST_DIR=./exercises/chapter13/
  - TEST_DIR=./exercises/chapter14/
  
install:
  - npm install -g bower purescript pulp
script:
  - cd $TEST_DIR
  - bower install 
  - pulp build

  
